#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "22012ad19b8b423f9663363fe1e9e0a6" }
]

[assets]
directory = "./public"
